/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz;

import Libros.GestionLibro;
import Presentacion.App;
import Tabla.ModeladorTablas;
import modelo.enums.CategoriasLibros;

/**
 *
 * @author raquelrojas
 */
public class Buscar extends javax.swing.JDialog {

    /**
     * Creates new form Buscar
     */
    
    public Buscar() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtNombre = new javax.swing.JTextField();
        txtLibreria = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtDesde = new javax.swing.JTextField();
        txtHasta = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        filtrar = new javax.swing.JToggleButton();
        jLabel7 = new javax.swing.JLabel();
        boxTema = new javax.swing.JComboBox<>();
        btnMenu = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });
        getContentPane().add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 70, 254, -1));
        getContentPane().add(txtLibreria, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 180, 150, -1));

        jLabel2.setText("Nombre ");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, -1, -1));

        jLabel3.setText("Precio:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, -1, -1));

        jLabel4.setText("Librería");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, -1, -1));

        jLabel5.setText("Tema");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, -1, -1));

        txtDesde.setText("0");
        txtDesde.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDesdeActionPerformed(evt);
            }
        });
        getContentPane().add(txtDesde, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 260, 51, -1));

        txtHasta.setText("0");
        getContentPane().add(txtHasta, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 260, 71, -1));

        jLabel1.setText("desde");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 260, -1, -1));

        jLabel6.setText("hasta");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 260, -1, -1));

        filtrar.setText("Filtrar ");
        filtrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                filtrarActionPerformed(evt);
            }
        });
        getContentPane().add(filtrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 320, -1, -1));

        jLabel7.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel7.setText("Búsqueda de Libros");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 20, -1, -1));

        boxTema.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "NINGUNO", "INGENIERIA", "ADMINISTRACION", "CIENCIASNATURALES", "ARTES", "HISTORIA", "FICCION", "LITERATURA", "MATEMATICA", " " }));
        boxTema.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boxTemaActionPerformed(evt);
            }
        });
        getContentPane().add(boxTema, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 120, -1, -1));

        btnMenu.setText("Menú");
        btnMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuActionPerformed(evt);
            }
        });
        getContentPane().add(btnMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 320, -1, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondos-de-colores-lisos-claros.jpg"))); // NOI18N
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 430, 400));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void filtrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_filtrarActionPerformed

        String nombre, Libreria;
        CategoriasLibros Tema;
        double desde, hasta;
        
        nombre = txtNombre.getText();
        Tema = CategoriasLibros.valueOf(boxTema.getSelectedItem().toString());
        desde = Double.parseDouble(txtDesde.getText());
        hasta = Double.parseDouble(txtHasta.getText());
        Libreria = txtLibreria.getText();
        
         App.gestion_libro.filtrarLibreria(nombre, Tema, Libreria, desde, hasta);
        
       
        this.setVisible(false);
            
        LibroFiltrado principal = new LibroFiltrado();
        principal.setVisible(true);
        principal.setGestion_libro(App.gestion_libro);
        
        Object[] columnasLibros = new Object[] {"Issn","Nombre","Tema","Cant Vendida","Cant Disponible", "Descripcion", "Precio"};        
        principal.getTabla_libro().setModel(ModeladorTablas.generarModeloDeTabla(7, columnasLibros));
        principal.getTabla_libro().setAutoCreateRowSorter(true);
        principal.actualizarTabla();
    }//GEN-LAST:event_filtrarActionPerformed

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActionPerformed

    private void txtDesdeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDesdeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDesdeActionPerformed

    private void boxTemaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boxTemaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_boxTemaActionPerformed

    private void btnMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuActionPerformed
        Menu menu = new Menu();
        menu.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnMenuActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> boxTema;
    private javax.swing.JButton btnMenu;
    private javax.swing.JToggleButton filtrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField txtDesde;
    private javax.swing.JTextField txtHasta;
    private javax.swing.JTextField txtLibreria;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
